### PR TITLE
Update README.md to include more examples on how to ignore files

### PR DESCRIPTION
**Pull request by calebpeterson**
I thought it'd be helpful to provide a few more concrete examples on how to ignore multiple paths/files.

### CODE REVIEW

**Comment by calebpeterson** [comment]
@nadeesha would you mind giving this README update a quick look and let me know if it's ready to merge when you have a few moments please?

**Comment by nadeesha** [comment]
Thanks! Looks good.

**Comment by calebpeterson** [comment]
Thanks @nadeesha!

It does look like the test job is failing and I don't appear to be able to re-run it 🤔 Would you mind giving it a look when you've got a moment please?

**Comment by Zamiell** [comment]
thank you so much for this PR, it's exactly what I needed

**Comment by nadeesha** [comment]
Thanks @calebpeterson. Apologies for the delay.

**Pull request merged**
