### PR TITLE
Add more precise location

### PR DESCRIPTION
**Pull request by wcandillon**
I'm wrapping this module into an ESLint plugin and I would like to access more precise location

### CODE REVIEW

**Comment by nadeesha** [comment]
Thanks @wcandillon. This is a great improvement.

However, I noticed that the stdout had changed to JSON. This might affect some of the existing users today, who are using it as a CLI. Would there be a way to produce the JSON output on a CLI parameter? Maybe `--json` would print the output you have in this PR, and the absence of it will convert the JSON into the existing output?

You can check the integration test failure to see what the desired output should look like.

**Comment by wcandillon** [comment]
@nadeesha the integration failure is because of this extra output it looks like:

```
rm: cannot remove './integration/testproject/outfile': No such file or directory
```

Could you help me on what caused that?

**Comment by nadeesha** [comment]
I think the diff is entirely different 🤔 

The integration steps compare the currently produced output of the tests with a base file. The currently produced output is json, while the previously produced output is a grep friendly one-line-per-unused export output.

```
5. Diff between outputs 
The output was not the same as the base
---
1,135c1,15
< {
<   file: 'src/B.ts',
<   symbol: {
<     name: 'UnusedFooType',
<     start: { line: 9, column: 1 },
<     end: { line: 9, column: 31 },
<     usedInModule: false
<   }
< }
< {
<   file: 'src/C.ts',
<   symbol: {
<     start: { line: 1, column: 1 },
<     end: { line: 1, column: 25 },
<     usedInModule: false
<   }
< }
< {
<   file: 'src/dynamic/fail.ts',
<   symbol: {
<     name: 'bar',
<     start: { line: 3, column: 1 },
<     end: { line: 3, column: 25 },
<     usedInModule: false
<   }
< }
< {
<   file: 'src/wildcard/foo.ts',
<   symbol: {
<     name: 'vUnused',
<     start: { line: 5, column: 14 },
<     end: { line: 5, column: 27 },
<     usedInModule: false
<   }
< }
---
> src/B.ts:9 - UnusedFooType
> src/C.ts:9 - default
> src/cities.ts:1 - sepehub
> src/cities.ts:2 - kuariob
> src/cities.ts:4 - femvacsah
> src/cities.ts:5 - sijelup
> src/internal-uses.ts:5 - usedInThisFile (used in module)
> src/internal-uses.ts:7 - thisOneIsUnused
> src/internal-uses.ts:9 - UsedInThisFile (used in module)
> src/internal-uses.ts:11 - Unused
> src/internal-uses.ts:13 - Row (used in module)
> src/internal-uses.ts:17 - UnusedProps
> src/dynamic/fail.ts:1 - foo
> src/dynamic/fail.ts:3 - bar
> src/wildcard/foo.ts:5 - vUnused
rm: cannot remove './integration/testproject/outfile': No such file or directory
```

Since there are existing uses who do things like `ts-prune | grep -v foo`, the json output will break this behaviour.

Since you've already done a lot of good work getting the output in json, my suggestion is as follows:

1. Define a new CLI param `--json`
2. If `--json` is not supplied to the run, convert the out put to the existing format:

```
// something like this: 

if (!cliParam.json) {
  return results.map(result => {
     return `${result.file}:${result.symbol.start} - ${symbol.name}`;
  })
} else {
  return results;
}
```

What do you think?

**Comment by Zamiell** [comment]
@wcandillon Any updates on this? Eagarly awaiting ts-prune as an eslint plugin so that
1) it can be run in CI
2) TS projects can just use **one** tool for everything (i.e. eslint)

**Comment by wcandillon** [comment]
@Zamiell I'm hitting a tough issue with ESlint because for each file you need to parse/analyze the whole tree. I am wondering if there is a concept of session I could use to do this efficiently on Eslint.

**Comment by nadeesha** [comment]
I'm closing this due to the lack of activity. I'll re-open if anyone's interested in carrying the discussion forward.

**Comment by xanderfehsenfeld** [comment]
> I'm closing this due to the lack of activity. I'll re-open if anyone's interested in carrying the discussion forward.

I'm interested! A more precise location would be helpful for creating a ts-prune github bot. The previously mentioned `--json` option would work.

**Pull request closed without merging**
