### PR TITLE
Add a fix mode that automatically fixes unused exports (revival)

### LINKED ISSUE #98: [FEATURE] Add option for process.exit() with code greater than zero for build failure
My company is using ts-prune during the pipeline execution to determine whether the developer left some deadcode in the branch.
Currently we have a script that executes the npm task and takes result from ts prune.
Would be good to put it as a config flag to fail the build if it detects the unused code

### PR DESCRIPTION
**Pull request by phiresky**
Revival of #67. Also fixes #98.

I added git status checking, if the git repo containing the given project has any uncommitted changes, it will refuse to modify it.

### CODE REVIEW

**Comment by phiresky** [comment]
CI runs into out of memory for some reason, not sure why?

**Comment by nadeesha** [comment]
@phiresky Would you be able to merge master and try again? (Sorry about the delay in response)

**Comment by phiresky** [comment]
It's still runnnig out of memory? :o i don't think this changes anything that should affect that?

**Comment by nadeesha** [comment]
I'm not really sure why this is the case. It might be that `.forEach` is called synchronously but `decl.remove()` is executed async, which makes too many file handles to be opened at the same time.

**Comment by mgwidmann** [comment]
would like to see this merged, is there an update?

**Comment by nadeesha** [comment]
Please open this once you have a change to clean this up. I'm closing this for now.

**Pull request closed without merging**
