### PR TITLE
Multiple skip regex

### PR DESCRIPTION
**Pull request by sviande**
Hi, this PR allow users to specify multiple skip patterns.
In the first commit the RegExp is created at startup instead of creating a new one for each files.

### CODE REVIEW

**Comment by nadeesha** [comment]
Thanks for submitting this PR.

I'm curious as to the use case of definining multiple regexes. As I understand, you can define a single regex in a way that captures multiple patterns. (ex: `/(ts|tsx)/`) Could you help me understand your reasoning?

**Comment by sviande** [comment]
Hi,  i want to be explicit, in my code base i need to exlude tests files `-s "*.test.ts$"` and  declaration of endpoint `-s "expose/*.ts$"`.

I can create a single regex but for clarity i prefer one regex for each case.

**Comment by nadeesha** [comment]
Thanks for that clarification.

However, given that there's a regex native method of doing what you're doing, I'm not really sure whether having this option as a feature would be universally helpful.

Maybe you can achieve explicit regex-ing via variables? If you're using bash:

```bash
TEST_FILES="foo"
SOMETHING_ELSE="bar"

ts-prune -s "/($TEST_FILES|$SOMETHING_ELSE)/
```

How does that sound?

**Comment by sviande** [comment]
Yes i can do that way, I'm not fan but I understand the costs of maintenability for this feature.

You can close this PR, maybe cherry-picking the first commit prevents re-creating the regex multiple times.

**Comment by nadeesha** [comment]
@sviande Feel free to send a PR with a cherry-picked commit. I'll close this now 🙇

**Pull request closed without merging**
